// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package protoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerFlag int32

const (
	ServerFlag_REGISTER    ServerFlag = 0
	ServerFlag_GETWORKER   ServerFlag = 1
	ServerFlag_REGETWORKER ServerFlag = 2
)

var ServerFlag_name = map[int32]string{
	0: "REGISTER",
	1: "GETWORKER",
	2: "REGETWORKER",
}

var ServerFlag_value = map[string]int32{
	"REGISTER":    0,
	"GETWORKER":   1,
	"REGETWORKER": 2,
}

func (x ServerFlag) String() string {
	return proto.EnumName(ServerFlag_name, int32(x))
}

func (ServerFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

type MsgToServer struct {
	Ipstring             string     `protobuf:"bytes,1,opt,name=ipstring,proto3" json:"ipstring,omitempty"`
	Prostring            string     `protobuf:"bytes,2,opt,name=prostring,proto3" json:"prostring,omitempty"`
	Flag                 ServerFlag `protobuf:"varint,3,opt,name=flag,proto3,enum=protoc.ServerFlag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgToServer) Reset()         { *m = MsgToServer{} }
func (m *MsgToServer) String() string { return proto.CompactTextString(m) }
func (*MsgToServer) ProtoMessage()    {}
func (*MsgToServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *MsgToServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgToServer.Unmarshal(m, b)
}
func (m *MsgToServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgToServer.Marshal(b, m, deterministic)
}
func (m *MsgToServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToServer.Merge(m, src)
}
func (m *MsgToServer) XXX_Size() int {
	return xxx_messageInfo_MsgToServer.Size(m)
}
func (m *MsgToServer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToServer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToServer proto.InternalMessageInfo

func (m *MsgToServer) GetIpstring() string {
	if m != nil {
		return m.Ipstring
	}
	return ""
}

func (m *MsgToServer) GetProstring() string {
	if m != nil {
		return m.Prostring
	}
	return ""
}

func (m *MsgToServer) GetFlag() ServerFlag {
	if m != nil {
		return m.Flag
	}
	return ServerFlag_REGISTER
}

type MsgToClient struct {
	Ipstring             string   `protobuf:"bytes,1,opt,name=ipstring,proto3" json:"ipstring,omitempty"`
	Prostring            string   `protobuf:"bytes,2,opt,name=prostring,proto3" json:"prostring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgToClient) Reset()         { *m = MsgToClient{} }
func (m *MsgToClient) String() string { return proto.CompactTextString(m) }
func (*MsgToClient) ProtoMessage()    {}
func (*MsgToClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *MsgToClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgToClient.Unmarshal(m, b)
}
func (m *MsgToClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgToClient.Marshal(b, m, deterministic)
}
func (m *MsgToClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToClient.Merge(m, src)
}
func (m *MsgToClient) XXX_Size() int {
	return xxx_messageInfo_MsgToClient.Size(m)
}
func (m *MsgToClient) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToClient.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToClient proto.InternalMessageInfo

func (m *MsgToClient) GetIpstring() string {
	if m != nil {
		return m.Ipstring
	}
	return ""
}

func (m *MsgToClient) GetProstring() string {
	if m != nil {
		return m.Prostring
	}
	return ""
}

func init() {
	proto.RegisterEnum("protoc.ServerFlag", ServerFlag_name, ServerFlag_value)
	proto.RegisterType((*MsgToServer)(nil), "protoc.MsgToServer")
	proto.RegisterType((*MsgToClient)(nil), "protoc.MsgToClient")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc9, 0x4a, 0xf9, 0x5c,
	0xdc, 0xbe, 0xc5, 0xe9, 0x21, 0xf9, 0xc1, 0x60, 0x49, 0x21, 0x29, 0x2e, 0x8e, 0xcc, 0x82, 0xe2,
	0x92, 0xa2, 0xcc, 0xbc, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x86,
	0x8b, 0xb3, 0xa0, 0x28, 0x1f, 0x2a, 0xc9, 0x04, 0x96, 0x44, 0x08, 0x08, 0xa9, 0x71, 0xb1, 0xa4,
	0xe5, 0x24, 0xa6, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0x41, 0xac, 0x49, 0xd6, 0x83,
	0x98, 0xeb, 0x96, 0x93, 0x98, 0x1e, 0x04, 0x96, 0x57, 0x72, 0x87, 0x5a, 0xe8, 0x9c, 0x93, 0x99,
	0x9a, 0x57, 0x42, 0xbe, 0x85, 0x5a, 0x56, 0x5c, 0x5c, 0x08, 0xc3, 0x85, 0x78, 0xb8, 0x38, 0x82,
	0x5c, 0xdd, 0x3d, 0x83, 0x43, 0x5c, 0x83, 0x04, 0x18, 0x84, 0x78, 0xb9, 0x38, 0xdd, 0x5d, 0x43,
	0xc2, 0xfd, 0x83, 0xbc, 0x5d, 0x83, 0x04, 0x18, 0x85, 0xf8, 0xb9, 0xb8, 0x83, 0x5c, 0x11, 0x02,
	0x4c, 0x49, 0x10, 0xdf, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x12, 0xbd, 0x74, 0x67, 0x14,
	0x01, 0x00, 0x00,
}
