// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute.proto

package protoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataFlag int32

const (
	DataFlag_DATAINT32 DataFlag = 0
	DataFlag_DATAINT64 DataFlag = 1
	DataFlag_DATAFLOAT DataFlag = 2
)

var DataFlag_name = map[int32]string{
	0: "DATAINT32",
	1: "DATAINT64",
	2: "DATAFLOAT",
}

var DataFlag_value = map[string]int32{
	"DATAINT32": 0,
	"DATAINT64": 1,
	"DATAFLOAT": 2,
}

func (x DataFlag) String() string {
	return proto.EnumName(DataFlag_name, int32(x))
}

func (DataFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{0}
}

type Opr int32

const (
	Opr_ADD Opr = 0
	Opr_SUB Opr = 1
	Opr_MUL Opr = 2
	Opr_DIV Opr = 3
)

var Opr_name = map[int32]string{
	0: "ADD",
	1: "SUB",
	2: "MUL",
	3: "DIV",
}

var Opr_value = map[string]int32{
	"ADD": 0,
	"SUB": 1,
	"MUL": 2,
	"DIV": 3,
}

func (x Opr) String() string {
	return proto.EnumName(Opr_name, int32(x))
}

func (Opr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{1}
}

type ResFlag int32

const (
	ResFlag_FALSE    ResFlag = 0
	ResFlag_RESINT32 ResFlag = 1
	ResFlag_RESINT64 ResFlag = 2
	ResFlag_RESFLOAT ResFlag = 3
)

var ResFlag_name = map[int32]string{
	0: "FALSE",
	1: "RESINT32",
	2: "RESINT64",
	3: "RESFLOAT",
}

var ResFlag_value = map[string]int32{
	"FALSE":    0,
	"RESINT32": 1,
	"RESINT64": 2,
	"RESFLOAT": 3,
}

func (x ResFlag) String() string {
	return proto.EnumName(ResFlag_name, int32(x))
}

func (ResFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{2}
}

type ServerFlag int32

const (
	ServerFlag_REGISTER    ServerFlag = 0
	ServerFlag_GETWORKER   ServerFlag = 1
	ServerFlag_REGETWORKER ServerFlag = 2
)

var ServerFlag_name = map[int32]string{
	0: "REGISTER",
	1: "GETWORKER",
	2: "REGETWORKER",
}

var ServerFlag_value = map[string]int32{
	"REGISTER":    0,
	"GETWORKER":   1,
	"REGETWORKER": 2,
}

func (x ServerFlag) String() string {
	return proto.EnumName(ServerFlag_name, int32(x))
}

func (ServerFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{3}
}

type ComData struct {
	Firstnum             string   `protobuf:"bytes,1,opt,name=firstnum,proto3" json:"firstnum,omitempty"`
	Secondnum            string   `protobuf:"bytes,2,opt,name=secondnum,proto3" json:"secondnum,omitempty"`
	Flag                 DataFlag `protobuf:"varint,3,opt,name=flag,proto3,enum=protoc.DataFlag" json:"flag,omitempty"`
	Opr                  Opr      `protobuf:"varint,4,opt,name=opr,proto3,enum=protoc.Opr" json:"opr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComData) Reset()         { *m = ComData{} }
func (m *ComData) String() string { return proto.CompactTextString(m) }
func (*ComData) ProtoMessage()    {}
func (*ComData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{0}
}

func (m *ComData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComData.Unmarshal(m, b)
}
func (m *ComData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComData.Marshal(b, m, deterministic)
}
func (m *ComData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComData.Merge(m, src)
}
func (m *ComData) XXX_Size() int {
	return xxx_messageInfo_ComData.Size(m)
}
func (m *ComData) XXX_DiscardUnknown() {
	xxx_messageInfo_ComData.DiscardUnknown(m)
}

var xxx_messageInfo_ComData proto.InternalMessageInfo

func (m *ComData) GetFirstnum() string {
	if m != nil {
		return m.Firstnum
	}
	return ""
}

func (m *ComData) GetSecondnum() string {
	if m != nil {
		return m.Secondnum
	}
	return ""
}

func (m *ComData) GetFlag() DataFlag {
	if m != nil {
		return m.Flag
	}
	return DataFlag_DATAINT32
}

func (m *ComData) GetOpr() Opr {
	if m != nil {
		return m.Opr
	}
	return Opr_ADD
}

type ComRes struct {
	Res                  string   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Flag                 ResFlag  `protobuf:"varint,2,opt,name=flag,proto3,enum=protoc.ResFlag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComRes) Reset()         { *m = ComRes{} }
func (m *ComRes) String() string { return proto.CompactTextString(m) }
func (*ComRes) ProtoMessage()    {}
func (*ComRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{1}
}

func (m *ComRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComRes.Unmarshal(m, b)
}
func (m *ComRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComRes.Marshal(b, m, deterministic)
}
func (m *ComRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComRes.Merge(m, src)
}
func (m *ComRes) XXX_Size() int {
	return xxx_messageInfo_ComRes.Size(m)
}
func (m *ComRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ComRes.DiscardUnknown(m)
}

var xxx_messageInfo_ComRes proto.InternalMessageInfo

func (m *ComRes) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func (m *ComRes) GetFlag() ResFlag {
	if m != nil {
		return m.Flag
	}
	return ResFlag_FALSE
}

type MsgToServer struct {
	Ipstring             string     `protobuf:"bytes,1,opt,name=ipstring,proto3" json:"ipstring,omitempty"`
	Prostring            string     `protobuf:"bytes,2,opt,name=prostring,proto3" json:"prostring,omitempty"`
	Flag                 ServerFlag `protobuf:"varint,3,opt,name=flag,proto3,enum=protoc.ServerFlag" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgToServer) Reset()         { *m = MsgToServer{} }
func (m *MsgToServer) String() string { return proto.CompactTextString(m) }
func (*MsgToServer) ProtoMessage()    {}
func (*MsgToServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a04c0385a1d134f, []int{2}
}

func (m *MsgToServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgToServer.Unmarshal(m, b)
}
func (m *MsgToServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgToServer.Marshal(b, m, deterministic)
}
func (m *MsgToServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgToServer.Merge(m, src)
}
func (m *MsgToServer) XXX_Size() int {
	return xxx_messageInfo_MsgToServer.Size(m)
}
func (m *MsgToServer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgToServer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgToServer proto.InternalMessageInfo

func (m *MsgToServer) GetIpstring() string {
	if m != nil {
		return m.Ipstring
	}
	return ""
}

func (m *MsgToServer) GetProstring() string {
	if m != nil {
		return m.Prostring
	}
	return ""
}

func (m *MsgToServer) GetFlag() ServerFlag {
	if m != nil {
		return m.Flag
	}
	return ServerFlag_REGISTER
}

func init() {
	proto.RegisterEnum("protoc.DataFlag", DataFlag_name, DataFlag_value)
	proto.RegisterEnum("protoc.Opr", Opr_name, Opr_value)
	proto.RegisterEnum("protoc.ResFlag", ResFlag_name, ResFlag_value)
	proto.RegisterEnum("protoc.ServerFlag", ServerFlag_name, ServerFlag_value)
	proto.RegisterType((*ComData)(nil), "protoc.ComData")
	proto.RegisterType((*ComRes)(nil), "protoc.ComRes")
	proto.RegisterType((*MsgToServer)(nil), "protoc.MsgToServer")
}

func init() { proto.RegisterFile("compute.proto", fileDescriptor_7a04c0385a1d134f) }

var fileDescriptor_7a04c0385a1d134f = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0x75, 0x12, 0x9f, 0x9a, 0xeb, 0xf3, 0x39, 0xdc, 0x95, 0x3c, 0x5a, 0x10, 0x5b, 0x8a, 0xcd,
	0xc2, 0x85, 0x8a, 0x85, 0x2e, 0x5a, 0x52, 0x13, 0x45, 0xaa, 0x0d, 0x4c, 0x62, 0xbb, 0x4e, 0xd3,
	0x18, 0x04, 0xe3, 0x84, 0x49, 0xec, 0x6f, 0xe8, 0xcf, 0x2e, 0x93, 0x0f, 0xd3, 0xae, 0x72, 0x3e,
	0xe6, 0xde, 0x73, 0x0f, 0x04, 0x3a, 0x3e, 0x8f, 0xe2, 0x53, 0x1a, 0x8c, 0x62, 0xc1, 0x53, 0x8e,
	0x8d, 0xec, 0xe3, 0x0f, 0xbe, 0x08, 0x34, 0xe7, 0x3c, 0x32, 0xbd, 0xd4, 0xc3, 0xff, 0xd0, 0xda,
	0xed, 0x45, 0x92, 0x1e, 0x4f, 0x51, 0x8f, 0xf4, 0xc9, 0x50, 0x63, 0x67, 0x8e, 0x17, 0xa0, 0x25,
	0x81, 0xcf, 0x8f, 0x1f, 0xd2, 0x54, 0x32, 0xb3, 0x12, 0xf0, 0x1a, 0xea, 0xbb, 0x83, 0x17, 0xf6,
	0xd4, 0x3e, 0x19, 0xfe, 0x1b, 0xd3, 0x3c, 0xc3, 0x1f, 0xc9, 0xad, 0x8b, 0x83, 0x17, 0xb2, 0xcc,
	0xc5, 0x4b, 0x50, 0x79, 0x2c, 0x7a, 0xf5, 0xec, 0x51, 0xbb, 0x7c, 0x64, 0xc7, 0x82, 0x49, 0x7d,
	0xf0, 0x08, 0x8d, 0x39, 0x8f, 0x58, 0x90, 0x20, 0x05, 0x55, 0x04, 0x49, 0x71, 0x83, 0x84, 0x78,
	0x55, 0x04, 0x28, 0xd9, 0x6c, 0xb7, 0x9c, 0x65, 0x41, 0x52, 0xed, 0x1f, 0x70, 0x68, 0x6f, 0x92,
	0xd0, 0xe5, 0x4e, 0x20, 0x3e, 0x03, 0x21, 0xeb, 0xec, 0xe3, 0x24, 0x15, 0xfb, 0x63, 0x58, 0xd6,
	0x29, 0xb9, 0xac, 0x13, 0x0b, 0x5e, 0x98, 0x45, 0x9d, 0xb3, 0x80, 0x37, 0xbf, 0xea, 0x60, 0x99,
	0x96, 0xef, 0xad, 0x02, 0xf5, 0x3b, 0x68, 0x95, 0x15, 0xb1, 0x03, 0x9a, 0x69, 0xb8, 0xc6, 0xea,
	0xc5, 0x9d, 0x8c, 0x69, 0xed, 0x07, 0x9d, 0x4d, 0x29, 0x29, 0xe9, 0x62, 0x6d, 0x1b, 0x2e, 0x55,
	0xf4, 0x5b, 0x50, 0xed, 0x58, 0x60, 0x13, 0x54, 0xc3, 0x34, 0x69, 0x4d, 0x02, 0x67, 0xfb, 0x44,
	0x89, 0x04, 0x9b, 0xed, 0x9a, 0x2a, 0x12, 0x98, 0xab, 0x57, 0xaa, 0xea, 0x0f, 0xd0, 0x2c, 0x5a,
	0xa2, 0x06, 0x7f, 0x16, 0xc6, 0xda, 0xb1, 0x68, 0x0d, 0xff, 0x42, 0x8b, 0x59, 0x4e, 0x1e, 0x46,
	0x2a, 0x36, 0x9b, 0x52, 0xa5, 0x60, 0x79, 0x94, 0xaa, 0xdf, 0x03, 0x54, 0x77, 0xe7, 0xde, 0x72,
	0xe5, 0xb8, 0x16, 0xcb, 0x8f, 0x5c, 0x5a, 0xee, 0x9b, 0xcd, 0x9e, 0x2d, 0x46, 0x09, 0x76, 0xa1,
	0xcd, 0xac, 0x4a, 0x50, 0xde, 0xf3, 0x9f, 0x64, 0xf2, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xf9,
	0x37, 0xa2, 0x3c, 0x02, 0x00, 0x00,
}
